
import dotenv from "dotenv";
import { bookDescriptions } from "./seedDesc";

const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

dotenv.config();


async function main() {
  await prisma.book.createMany({
    data: [
      {
        title: "Horus Rising",
        author: "Dan Abnett",
        pages: 416,
        desc: bookDescriptions["Horus Rising"].desc, 
        image: bookDescriptions["Horus Rising"].image,
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "https://www.amazon.com/Horus-Rising-Heresy-Dan-Abnett/dp/184970743X/ref=tmm_pap_swatch_0?_encoding=UTF8&dib_tag=se&dib=eyJ2IjoiMSJ9.PN9YjGmXm6g_g9OJrIz_indHOPaO84Z3b8g_Ww-l9Smc5YWzvGYc_8QeKjdh-BPWOQNaw6itvrrvwtuZKNOMZdvbyo1CcEvK_n8ZmSIUClFZJrevwszGxCuJzcUbN4qT61VE64tbkg3AmyeAUGRmDQ2JGVNgqfaiTuS_kt8O2n4lKnBSqX8reuouWpugJVHkOzMU4GOWSQARG1Zq2J9KwzsNHMLZX6f7dLd3JNy9Kjw.ZTgLQnTfTxBmu8alC-aythVvsqHhxFLv3vgYHbKyOhA&qid=1719427240&sr=1-1",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "False Gods",
        author: "Graham Mcneill",
        pages: 416,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Galaxy in Flames",
        author: "Ben Counter",
        pages: 416,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "The Flight of the Eisenstein",
        author: "James Swallow",
        pages: 416,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Fulgrim",
        author: "Graham Mcneill",
        pages: 516,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Descent of Angels",
        author: "Michel Scanlon",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Legion",
        author: "Dan Abnett",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Battle for the Abyss",
        author: "Ben Counter",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Mechanicum",
        author: "Graham Mcneil",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "Mechanicus"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Tales of Heresy",
        author:
          "Dan Abnett, Mike Lee, Anthony Reynolds, James Swallow, Gav Thorpe, Graham Mcneill, Matthew Farrer",
        pages: 260,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Fallen Angels",
        author: "Mike Lee",
        pages: 416,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "A Thousand Sons",
        author: "Graham Mcneill",
        pages: 560,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Nemesis",
        author: "James Swallow",
        pages: 512,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "The First Heretic",
        author: "Aaron Dembski-Bowden",
        pages: 483,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Prospero Burns",
        author: "Dan Abnett",
        pages: 416,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Age of Darkness",
        author:
          "Dan Abnett, Graham McNeill, James Swallow , Aaron-Dembski Bowden, Rob Sanders, Gav Thorpe, Nick Kyme, John French, Chris Wraight",
        pages: 326,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "The Outcast Dead",
        author: "Graham Mcneill",
        pages: 468,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Deliverance Lost",
        author: "Gav Thorpe",
        pages: 484,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Know No Fear",
        author: "Dan Abnett",
        pages: 320,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Macragge's Honour",
        author: "Dan Abnett, Neil Roberts",
        pages: 128,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "The Honoured",
        author: "Rob Sanders",
        pages: 240,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "The Unburdened: Betrayal at Calth",
        author: "David Annandale",
        pages: 191,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "The Primarchs",
        author: "Graham Mcneill, Gav Thorpe, Nick Kyme, Rob Sanders",
        pages: 416,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Fear to Tread",
        author: "James Swallow",
        pages: 439,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "https://www.amazon.com/Tread-Horus-Heresy-James-Swallow/dp/1849701962/ref=tmm_mmp_swatch_0?_encoding=UTF8&qid=&sr=",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Shadows of Treachery",
        author:
          "Graham Mcneill, Gav Thorpe, Dan Abnett, John French, Aaron-Dembski Bowden ",
        pages: 322,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "https://www.amazon.com/Shadows-Treachery-Horus-Heresy-Christian/dp/1849703477/ref=tmm_mmp_swatch_0?_encoding=UTF8&qid=&sr=",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Angel Exterminatus",
        author: "Graham Mcneill",
        pages: 416,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "https://www.amazon.com/Angel-Exterminatus-Heresy-Hardcover-Warhammer/dp/1849702098/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=&sr=",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Tallarn: Ironclad",
        author: "",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "Mechanicus"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Betrayer",
        author: "Aaron Dembski-Bowden",
        pages: 416,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "https://www.amazon.com/gp/product/1849703892?ref_=dbs_m_mng_rwt_calw_tpbk_23&storeType=ebooks",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Mark of Calth",
        author:
          "Guy Haley , Graham McNeill , Anthony Reynolds , David Annandale , Rob Sanders , Aaron Dembski-Bowden , John French , Dan Abnett ",
        pages: 416,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "https://www.amazon.com/Mark-Calth-Horus-Heresy/dp/1849705747/ref=tmm_mmp_swatch_0?_encoding=UTF8&qid=&sr=",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Promethean Sun",
        author: "",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Vulkan Lives",
        author: "Nick Kyme",
        pages: 464,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "https://www.amazon.com/Vulkan-Lives-Heresy-Hardcover-Warhammer/dp/1849703167/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=&sr=",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "The Unremembered Empire",
        author: "Dan Abnett",
        pages: 416,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "https://www.amazon.com/gp/product/1849706921?ref_=dbs_m_mng_rwt_calw_tpbk_26&storeType=ebooks",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Scars",
        author: "Chris Wraight",
        pages: 416,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "https://www.amazon.com/gp/product/1849707502?ref_=dbs_m_mng_rwt_calw_tpbk_27&storeType=ebooks",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Wolf King",
        author: "",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Vengeful Spirit",
        author: "Graham Mcneill",
        pages: 544,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "https://www.amazon.com/Vengeful-Spirit-Heresy-Graham-McNeill/dp/1849708312/ref=tmm_pap_swatch_0?_encoding=UTF8&qid=&sr=",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "The Damnation of Pythos",
        author: "David Annandale",
        pages: 416,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "https://www.amazon.com/gp/product/1849707529?ref_=dbs_m_mng_rwt_calw_tpbk_29&storeType=ebooks",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Legacies of Betrayal",
        author:
          "Graham McNeill , Aaron Dembski-Bowden, Nick Kyme , Chris Wraight , Guy Haley , John French , David Annandale , Gav Thorpe , Anthony Reynolds",
        pages: 448,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "https://www.amazon.com/Legacies-Betrayal-Galaxy-Hardcover-Warhammer/dp/1849707944/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=&sr=",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Deathfire",
        author: "Nick Kyme",
        pages: 508,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "https://www.amazon.com/Deathfire-Ruinstorm-Heresy-Hardcover-Warhammer/dp/1849708924/ref=tmm_hrd_swatch_0?_encoding=UTF8&qid=&sr=",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "War Without End",
        author:
          "Rob Sanders, Aaron Dembski-Bowden, Andy Smillie, Chris Wraight, David Annandale, Gav Thorpe, Graham McNeill, Guy Haley, James Swallow, John French, Nick Kyme ",
        pages: 544,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "https://www.amazon.com/War-Without-End-Horus-Heresy/dp/1784964549/ref=tmm_pap_swatch_0?_encoding=UTF8&qid=&sr=",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Pharos",
        author: "Guy Haley",
        pages: 432,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "https://www.amazon.com/gp/product/1784964743?ref_=dbs_m_mng_rwt_calw_tpbk_33&storeType=ebooks",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "The Seventh Serpent",
        author: "",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Eye of Terra",
        author:
          "Graham Mcneill, Aaron Dembski-Bowden, Chris Wraight, Gav Thorpe, Matthew Farrer, Rob Sanders, Nick Kyme, Andy Smillie, John French, David Annandale , Guy Haley ",
        pages: 416,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "https://www.amazon.com/gp/product/1784964557?ref_=dbs_m_mng_rwt_calw_tpbk_34&storeType=ebooks",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "The Path of Heaven",
        author: "",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "The Silent War",
        author: "",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Angels of Caliban",
        author: "",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Praetorian of Dorn",
        author: "",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Corax",
        author: "",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "The Master of Mankind",
        author: "",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Garro: Weapon of Fate",
        author: "",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Shattered Legions",
        author: "",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "The Crimson King",
        author: "",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "The Solar War",
        author: "John French",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "The Lost and the Damned",
        author: "Guy Haley",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "The First Wall",
        author: "Gav Thorpe",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Sons of the Selenar",
        author: "Graham McNeill",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Saturnine",
        author: "Dan Abnett",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "The Fury of Magnus",
        author: "Graham McNeill",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Mortis",
        author: "John French",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Warhawk",
        author: "Chris Wraight",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Echoes of Eternity",
        author: "Aaron Dembski-Bowden",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Garro: Knight of Grey",
        author: "James Swallow",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "The End and the Death: Volume I",
        author: "Dan Abnett",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "The End and the Death: Volume II",
        author: "",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "astartes"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Roboute Guilliman: Lord of Ultramar",
        author: "David Annandale",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "primarch", "astartes", "ultramarines"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Leman Russ: The Great Wolf",
        author: "Chris Wraight",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "primarch", "astartes", "space wolves"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Magnus the Red: Master of Prospero",
        author: "Graham McNeill",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "primarch", "astartes", "thousand sons"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Perturabo: Hammer of Olympia",
        author: "Guy Haley",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "primarch", "astartes", "iron warriors"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Lorgar: Bearer of the Word",
        author: "Gav Thorpe",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "primarch", "astartes", "word bearers"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Fulgrim: The Palatine Phoenix",
        author: "Josh Reynolds",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "primarch", "astartes", "emperor's children"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Ferrus Manus: The Gorgon of Medusa",
        author: "David Guymer",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "primarch", "astartes", "iron hands"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Jaghatai Khan: Warhawk of Chogoris",
        author: "Chris Wraight",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "primarch", "astartes", "white scars"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Vulkan: Lord of Drakes",
        author: "David Annandale",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "primarch", "astartes", "salamanders"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Corax: Lord of Shadows",
        author: "Guy Haley",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "primarch", "astartes", "raven guard"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Angron: Slave of Nuceria",
        author: "Ian St. Martin",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "primarch", "astartes", "world eaters"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Konrad Curze: The Night Haunter",
        author: "Guy Haley",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "primarch", "astartes", "night lords"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Lion El'Jonson: Lord of the First",
        author: "David Guymer",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "primarch", "astartes", "dark angels"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Alpharius: Head of the Hydra",
        author: "Mike Brooks",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "primarch", "astartes", "alpha legion"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Mortarion: The Pale King",
        author: "David Annandale",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "primarch", "astartes", "death guard"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Rogal Dorn: The Emperor's Crusader",
        author: "Gav Thorpe",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "primarch", "astartes", "imperial fists"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Sanguinius: The Great Angel",
        author: "Chris Wraight",
        pages: 0,
        desc: "",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "primarch", "astartes", "blood angels"],
        link: "",
        rating: null,
        quotes: "",
        summary: "",
      },
    ],
  });
}

main()
