
import dotenv from "dotenv";

//1350 - Omnibuses

const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

dotenv.config();


async function main() {
  await prisma.book.createMany({
    data: [
      {
        title: "Horus Rising",
        author: "Dan Abnett",
        pages: 416,
        desc: "At the dawn of the 31st millennium, the Emperor of Mankind has led humanity to the stars and united a thousand worlds under the Imperium. The Great Crusade to reunite humanity under the banner of the Imperium is at its height, and the Emperor’s favored son, Warmaster Horus, has been tasked with continuing the Crusade in the Emperor’s absence. But treachery from within the ranks of the Legions begins to surface, and Horus himself faces a momentous decision that could shatter the fragile unity of the Imperium. The seeds of the galaxy-spanning Heresy are sown in this gripping opening novel of the Horus Heresy series.",
        image:
          "https://m.media-amazon.com/images/I/81t0zZyR0BL._AC_UY327_FMwebp_QL65_.jpg", // Example Amazon book cover link
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "https://www.amazon.com/Horus-Rising-Heresy-Dan-Abnett/dp/184970743X/ref=tmm_pap_swatch_0?_encoding=UTF8&dib_tag=se&dib=eyJ2IjoiMSJ9.PN9YjGmXm6g_g9OJrIz_indHOPaO84Z3b8g_Ww-l9Smc5YWzvGYc_8QeKjdh-BPWOQNaw6itvrrvwtuZKNOMZdvbyo1CcEvK_n8ZmSIUClFZJrevwszGxCuJzcUbN4qT61VE64tbkg3AmyeAUGRmDQ2JGVNgqfaiTuS_kt8O2n4lKnBSqX8reuouWpugJVHkOzMU4GOWSQARG1Zq2J9KwzsNHMLZX6f7dLd3JNy9Kjw.ZTgLQnTfTxBmu8alC-aythVvsqHhxFLv3vgYHbKyOhA&qid=1719427240&sr=1-1",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "False Gods",
        author: "Graham McNeill",
        pages: 416,
        desc: "The Great Crusade continues, and Warmaster Horus struggles to keep the Imperium united as jealousy and suspicion set in. As he tries to consolidate his power and leadership, dark forces begin to turn him away from his father’s light. This novel shows the tragic turning point that starts Horus on the path of rebellion and introduces the sinister forces that will lead to the galaxy-wide civil war.",
        image:
          "https://m.media-amazon.com/images/I/91LRTcJ5yBL._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes", "chaos"],
        link: "https://www.amazon.com/False-Gods-Horus-Heresy/dp/1849707464",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Galaxy in Flames",
        author: "Ben Counter",
        pages: 416,
        desc: "The third novel in the Horus Heresy series focuses on the events leading up to and during the Istvaan III massacre, a defining moment where Horus reveals his full treachery. Loyalist Astartes are betrayed and slaughtered by their own brothers as Horus begins his open rebellion against the Emperor. The first brutal blows of the Horus Heresy are dealt, and the fate of the Imperium is forever altered.",
        image:
          "https://m.media-amazon.com/images/I/81NpbIE5S7L._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes", "chaos"],
        link: "https://www.amazon.com/Galaxy-in-Flames-Ben-Counter-audiobook/dp/B076B4GWJ7",
        rating: null,
        quotes: "",
        summary: "",
      },

      {
        title: "The Flight of the Eisenstein",
        author: "James Swallow",
        pages: 416,
        desc: "Captain Garro of the Death Guard is a loyal servant of the Emperor, but when he discovers Horus’s betrayal during the massacre at Istvaan III, he takes matters into his own hands. Escaping with a few loyalists aboard the ship Eisenstein, Garro attempts to warn the Emperor of Horus’s treachery, setting in motion events that will change the galaxy forever. This novel marks the start of Garro's journey as a major character in the series.",
        image:
          "https://m.media-amazon.com/images/I/91qldhtf-qL._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: [
          "siege of terra",
          "horus heresy",
          "astartes",
          "imperial loyalists",
        ],
        link: "https://www.amazon.se/Flight-Eisenstein-Heresy-Unfolds-No/dp/1844164594",
        rating: null,
        quotes: "",
        summary: "",
      },

      {
        title: "Fulgrim",
        author: "Graham McNeill",
        pages: 512,
        desc: "Fulgrim, the Primarch of the Emperor’s Children, has always strived for perfection, but his obsession leads him down a dark path. As Horus begins his rebellion, Fulgrim is drawn into the schemes of Chaos and becomes a willing agent of corruption. This novel explores the tragic fall of one of the most noble and proud Primarchs, leading to his ultimate damnation.",
        image:
          "https://m.media-amazon.com/images/I/71Qu99UOkgL._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes", "primarchs"],
        link: "https://www.amazon.com/Fulgrim-Graham-McNeill-audiobook/dp/B0765C7WYT",
        rating: null,
        quotes: "",
        summary: "",
      },

      {
        title: "Descent of Angels",
        author: "Mitchel Scanlon",
        pages: 416,
        desc: "The Dark Angels, the First Legion of the Emperor, are one of the most secretive and mysterious of the Space Marine Legions. This novel focuses on their origins and the rise of their Primarch, Lion El’Jonson. Set before the Heresy unfolds, it explores the early days of the Dark Angels and foreshadows the hidden agendas that will later tear them apart during the galaxy-wide conflict.",
        image:
          "https://m.media-amazon.com/images/I/81EVFHoLZ6L._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "dark angels", "primarchs"],
        link: "https://www.amazon.com/Descent-Angels-Horus-Heresy/dp/1849707510",
        rating: null,
        quotes: "",
        summary: "",
      },

      {
        title: "Legion",
        author: "Dan Abnett",
        pages: 416,
        desc: "The Alpha Legion, the most secretive of all the Space Marine Legions, are notorious for their cunning and subtlety. As Horus’s rebellion begins to unfold, the Alpha Legion must decide where their loyalties lie. Known for their cryptic nature and convoluted motives, this novel delves into the Alpha Legion’s complex involvement in the Horus Heresy and their role in shaping the future of the Imperium.",
        image:
          "https://m.media-amazon.com/images/I/81QJ9Nfwv6L._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "alpha legion", "primarchs"],
        link: "https://www.amazon.com/Legion-Horus-Heresy-Dan-Abnett/dp/1849707529",
        rating: null,
        quotes: "",
        summary: "",
      },

      {
        title: "Battle for the Abyss",
        author: "Ben Counter",
        pages: 416,
        desc: "A vast fleet of traitor World Eaters, Word Bearers, and Thousand Sons heads for the Ultramarines homeworld of Macragge, intent on laying waste to the loyalist realm. Captain Cestus of the Ultramarines leads a hastily assembled force to intercept the traitors and prevent the destruction of Ultramar. This novel showcases the brutal naval warfare and desperate battles in space that are a hallmark of the Horus Heresy.",
        image:
          "https://m.media-amazon.com/images/I/71r7xA1u53L._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "ultramarines", "astartes"],
        link: "https://www.amazon.com/Battle-Abyss-Horus-Heresy/dp/1849707537",
        rating: null,
        quotes: "",
        summary: "",
      },

      {
        title: "Mechanicum",
        author: "Graham McNeill",
        pages: 416,
        desc: "The Mechanicum, the mighty forge worlds that supply the Imperium with weapons, war machines, and technology, are divided as the Horus Heresy unfolds. Amidst the civil war, the forces of the Mechanicum must choose between loyalty to the Emperor or the rebellion of Horus. This novel focuses on the epic battles and hidden agendas within the Adeptus Mechanicus during the galaxy-wide conflict.",
        image:
          "https://m.media-amazon.com/images/I/81kVMPcyVjL._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "mechanicum", "technology"],
        link: "https://www.amazon.com/Mechanicum-Horus-Heresy-Graham-McNeill/dp/1849707545",
        rating: null,
        quotes: "",
        summary: "",
      },

      {
        title: "Tales of Heresy",
        author: "Various Authors",
        pages: 416,
        desc: "A collection of short stories exploring key events during the Horus Heresy. This anthology features multiple perspectives on the unfolding conflict, with tales of betrayal, loyalty, and heroism from both the Traitor and Loyalist forces. A must-read for fans who want to delve deeper into the lore and character backgrounds of the Horus Heresy universe.",
        image:
          "https://m.media-amazon.com/images/I/81YSYdOBZRL._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes", "short stories"],
        link: "https://www.amazon.com/Tales-Heresy-Horus/dp/1849707553",
        rating: null,
        quotes: "",
        summary: "",
      },

      {
        title: "Fallen Angels",
        author: "Mike Lee",
        pages: 416,
        desc: "The Dark Angels are divided. Luther and the Lion stand on the precipice of war. As Horus’s treachery continues, the Dark Angels are torn apart by internal conflict. This novel explores the growing rift between the Dark Angels, leading to the secrets and betrayals that define their chapter’s future.",
        image:
          "https://m.media-amazon.com/images/I/81J7qPU76eL._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "dark angels", "astartes"],
        link: "https://www.amazon.com/Fallen-Angels-Horus-Mike-Lee/dp/184970757X",
        rating: null,
        quotes: "",
        summary: "",
      },

      {
        title: "A Thousand Sons",
        author: "Graham McNeill",
        pages: 560,
        desc: "Magnus the Red is a genius of the arcane, and his Thousand Sons Legion are renowned for their psychic powers. But as they push the boundaries of forbidden knowledge, their obsession with sorcery draws the ire of the Emperor. This novel tells the tragic story of the Thousand Sons' fall from grace and the burning of Prospero, a pivotal moment in the Horus Heresy.",
        image:
          "https://m.media-amazon.com/images/I/91HD1Rr4obL._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "thousand sons", "astartes"],
        link: "https://www.amazon.com/Thousand-Sons-Horus-Heresy/dp/1849707588",
        rating: null,
        quotes: "",
        summary: "",
      },

      {
        title: "Nemesis",
        author: "James Swallow",
        pages: 416,
        desc: "The war between the Imperium and Horus’s forces extends beyond battlefields. Assassins are dispatched to kill Warmaster Horus, even as Horus sends his own death squads after key Imperial figures. This novel delves into the secretive world of assassins during the Horus Heresy, where a single kill can change the fate of the galaxy.",
        image:
          "https://m.media-amazon.com/images/I/81cq4MrHwOL._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "assassins", "imperium"],
        link: "https://www.amazon.com/Nemesis-Horus-Heresy-James-Swallow/dp/184970760X",
        rating: null,
        quotes: "",
        summary: "",
      },

      {
        title: "The First Heretic",
        author: "Aaron Dembski-Bowden",
        pages: 432,
        desc: "The Word Bearers were the first Legion to fall to Chaos, and their actions set the stage for the Horus Heresy. This novel explores their descent into heresy, following Lorgar and his followers as they discover dark truths and betray the Emperor’s trust. A deep look into one of the most pivotal events in the Heresy.",
        image:
          "https://m.media-amazon.com/images/I/91WAEzgzZNL._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "word bearers", "primarchs"],
        link: "https://www.amazon.com/First-Heretic-Horus-Heresy/dp/1849708118",
        rating: null,
        quotes: "",
        summary: "",
      },

      {
        title: "Prospero Burns",
        author: "Dan Abnett",
        pages: 448,
        desc: "The Space Wolves are the Emperor’s executioners, sent to deal with any who defy his will. This novel focuses on their role in the burning of Prospero, home of the Thousand Sons, and the complex relationship between Leman Russ and Magnus the Red. A companion novel to 'A Thousand Sons', it tells the other side of this tragic conflict.",
        image:
          "https://m.media-amazon.com/images/I/71yNPMHX8WL._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "space wolves", "primarchs"],
        link: "https://www.amazon.com/Prospero-Burns-Horus-Heresy-Abnett/dp/1849708193",
        rating: null,
        quotes: "",
        summary: "",
      },

      {
        title: "Age of Darkness",
        author: "Various Authors",
        pages: 416,
        desc: "A collection of short stories set during the aftermath of the Istvaan V massacre, as the galaxy spirals deeper into the Horus Heresy. The stories showcase both Traitor and Loyalist perspectives as the Imperium begins to crumble and hope fades. This anthology provides a deeper look into the grim realities of the war.",
        image:
          "https://m.media-amazon.com/images/I/91zS-H8XB8L._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes", "short stories"],
        link: "https://www.amazon.com/Age-Darkness-Horus-Heresy/dp/1849708223",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "The Outcast Dead",
        author: "Graham McNeill",
        pages: 416,
        desc: "While the war rages across the galaxy, some Astartes find themselves prisoners of circumstance. In the heart of the Imperium, a group of former traitor Astartes are held in a secret prison, only to discover a shocking secret about the Emperor’s plans. This novel explores the underbelly of the Imperium and the truth behind the Emperor’s greatest weapons.",
        image:
          "https://m.media-amazon.com/images/I/81XCGUzEV2L._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes", "imperium"],
        link: "https://www.amazon.com/Outcast-Dead-Horus-Heresy/dp/1849708193",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Deliverance Lost",
        author: "Gav Thorpe",
        pages: 416,
        desc: "Corax, Primarch of the Raven Guard, has returned from the massacre at Istvaan V. With his Legion in tatters, he sets out to rebuild, using the Emperor’s own genetic secrets to create new Astartes. But even as he fights to restore his Legion, treachery and infiltration threaten to destroy everything he’s fought for.",
        image:
          "https://m.media-amazon.com/images/I/71XDoYP7XmL._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "raven guard", "primarchs"],
        link: "https://www.amazon.com/Deliverance-Lost-Horus-Heresy-Thorpe/dp/1849708223",
        rating: null,
        quotes: "",
        summary: "",
      },

      {
        title: "Know No Fear",
        author: "Dan Abnett",
        pages: 416,
        desc: "The Ultramarines are taken by surprise when their supposed allies, the Word Bearers, launch a devastating attack. The Battle of Calth begins in this action-packed novel, showcasing the sheer brutality of the Horus Heresy and the strength of the Imperium’s finest defenders.",
        image:
          "https://m.media-amazon.com/images/I/91btfXtDlSL._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "ultramarines", "astartes"],
        link: "https://www.amazon.com/Know-No-Fear-Horus-Heresy/dp/1849702233",
        rating: null,
        quotes: "",
        summary: "",
      },

      // {
      //   title: "Macragge's Honour",
      //   author: "Dan Abnett, Neil Roberts",
      //   pages: 128,
      //   desc: "",
      //   image: "",
      //   isFinished: false,
      //   isReading: false,
      //   tags: ["siege of terra", "horus heresy", "astartes"],
      //   link: "",
      //   rating: null,
      //   quotes: "",
      //   summary: "",
      // },
      // {
      //   title: "The Honoured",
      //   author: "Rob Sanders",
      //   pages: 240,
      //   desc: "",
      //   image: "",
      //   isFinished: false,
      //   isReading: false,
      //   tags: ["siege of terra", "horus heresy", "astartes"],
      //   link: "",
      //   rating: null,
      //   quotes: "",
      //   summary: "",
      // },
      // {
      //   title: "The Unburdened: Betrayal at Calth",
      //   author: "David Annandale",
      //   pages: 191,
      //   desc: "",
      //   image: "",
      //   isFinished: false,
      //   isReading: false,
      //   tags: ["siege of terra", "horus heresy", "astartes"],
      //   link: "",
      //   rating: null,
      //   quotes: "",
      //   summary: "",
      // },

      {
        title: "The Primarchs",
        author: "Various Authors",
        pages: 416,
        desc: "This anthology of four novellas focuses on the Primarchs themselves, the demi-god leaders of the Legions. Each story delves into their personal struggles and decisions during the Horus Heresy, shedding light on their motivations and roles in the conflict.",
        image:
          "https://m.media-amazon.com/images/I/81k7N-Mj32L._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "primarchs", "anthology"],
        link: "https://www.amazon.com/Primarchs-Horus-Heresy-Nick-Kyme/dp/1849708142",
        rating: null,
        quotes: "",
        summary: "",
      },

      {
        title: "Fear to Tread",
        author: "James Swallow",
        pages: 560,
        desc: "Sanguinius, Primarch of the Blood Angels, faces a dark prophecy that threatens to turn his Legion to Chaos. Sent on a mission to the planet Signus Prime, the Blood Angels encounter terrifying Daemonic forces. This novel explores the tragic fall of Sanguinius and the true horrors of the Warp, as Horus's betrayal begins to claim more victims.",
        image:
          "https://m.media-amazon.com/images/I/91YWZP-+6nL._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "blood angels", "primarchs"],
        link: "https://www.amazon.com/Fear-Tread-Horus-James-Swallow/dp/1849702020",
        rating: null,
        quotes: "",
        summary: "",
      },

      {
        title: "Shadows of Treachery",
        author: "Various Authors",
        pages: 416,
        desc: "An anthology of stories showcasing key events and characters during the Horus Heresy. The collection features tales of treachery and heroism, focusing on the actions of both Traitor and Loyalist forces as the Heresy escalates. With contributions from renowned Black Library authors, this anthology is a must-read for fans of the series.",
        image:
          "https://m.media-amazon.com/images/I/91Rhpe1kDoL._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "anthology", "astartes"],
        link: "https://www.amazon.com/Shadows-Treachery-Horus-Heresy/dp/184970208X",
        rating: null,
        quotes: "",
        summary: "",
      },

      {
        title: "Angel Exterminatus",
        author: "Graham McNeill",
        pages: 448,
        desc: "Perturabo, Primarch of the Iron Warriors, and Fulgrim of the Emperor's Children seek to claim the power of an ancient weapon. Together, they journey to the mysterious world of the Eldar. However, their ambitions will lead them to uncover dark truths about the universe. This novel delves into the complex dynamics between these two Traitor Primarchs as the galaxy burns.",
        image:
          "https://m.media-amazon.com/images/I/91IpWNfsWWL._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: [
          "siege of terra",
          "horus heresy",
          "iron warriors",
          "emperor's children",
          "primarchs",
        ],
        link: "https://www.amazon.com/Angel-Exterminatus-Horus-Graham-McNeill/dp/1849704279",
        rating: null,
        quotes: "",
        summary: "",
      },

      // {
      //   title: "Tallarn: Ironclad",
      //   author: "",
      //   pages: 0,
      //   desc: "",
      //   image: "",
      //   isFinished: false,
      //   isReading: false,
      //   tags: ["siege of terra", "horus heresy", "Mechanicus"],
      //   link: "",
      //   rating: null,
      //   quotes: "",
      //   summary: "",
      // },
      {
        title: "Betrayer",
        author: "Aaron Dembski-Bowden",
        pages: 528,
        desc: "Lorgar and Angron, Primarchs of the Word Bearers and World Eaters, lead a devastating campaign against the Imperium. But as they push deeper into Loyalist space, they both face their own demons—literal and figurative. This novel explores the tragic fall of Angron, the nature of his transformation into a Daemon Primarch, and the deadly impact of Lorgar’s corruptive influence.",
        image:
          "https://m.media-amazon.com/images/I/81pGmhWn+mL._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: [
          "siege of terra",
          "horus heresy",
          "world eaters",
          "word bearers",
          "primarchs",
        ],
        link: "https://www.amazon.com/Betrayer-Horus-Heresy-Aaron-Dembski-Bowden/dp/1849705216",
        rating: null,
        quotes: "",
        summary: "",
      },

      {
        title: "Mark of Calth",
        author: "Various Authors",
        pages: 416,
        desc: "An anthology of short stories that continue the saga of the Ultramarines and their war against the Word Bearers, following the devastating events of 'Know No Fear'. The collection showcases the ongoing struggle at Calth, both on the surface and in the shadows, as Loyalist and Traitor forces clash.",
        image:
          "https://m.media-amazon.com/images/I/81nhEvIRuzL._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "ultramarines", "anthology"],
        link: "https://www.amazon.com/Mark-Calth-Horus-Library-Paperback/dp/1849705267",
        rating: null,
        quotes: "",
        summary: "",
      },

      // {
      //   title: "Promethean Sun",
      //   author: "",
      //   pages: 0,
      //   desc: "",
      //   image: "",
      //   isFinished: false,
      //   isReading: false,
      //   tags: ["siege of terra", "horus heresy", "astartes"],
      //   link: "",
      //   rating: null,
      //   quotes: "",
      //   summary: "",
      // },
      {
        title: "Vulkan Lives",
        author: "Nick Kyme",
        pages: 416,
        desc: "Vulkan, Primarch of the Salamanders, was thought dead after the Dropsite Massacre. But in truth, he has been captured and subjected to endless torment by the Night Lords. This novel explores Vulkan's unbreakable will and his quest for vengeance, while shedding light on the dark psyche of his captor, Konrad Curze, Primarch of the Night Lords.",
        image:
          "https://m.media-amazon.com/images/I/81yQwfUbtdL._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "salamanders", "primarchs"],
        link: "https://www.amazon.com/Vulkan-Lives-Horus-Heresy-Nick/dp/1849705976",
        rating: null,
        quotes: "",
        summary: "",
      },

      {
        title: "The Unremembered Empire",
        author: "Dan Abnett",
        pages: 416,
        desc: "Roboute Guilliman, Primarch of the Ultramarines, has carved out a bastion of hope amidst the chaos of the Horus Heresy. But even as he plans to reunite the scattered Loyalist forces, darker forces threaten his empire from within. This novel explores Guilliman's struggle to preserve the Imperium and the emergence of an unexpected savior.",
        image:
          "https://m.media-amazon.com/images/I/91I9k6hOtLL._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "ultramarines", "primarchs"],
        link: "https://www.amazon.com/Unremembered-Empire-Horus-Heresy/dp/1849705976",
        rating: null,
        quotes: "",
        summary: "",
      },

      {
        title: "Scars",
        author: "Chris Wraight",
        pages: 416,
        desc: "Jaghatai Khan, Primarch of the White Scars, is one of the most enigmatic figures in the Horus Heresy. As the galaxy tears itself apart, the Khan must decide where his Legion’s loyalty lies. This novel explores the culture of the White Scars and their struggle to find their place in the unfolding conflict, leading to a pivotal moment in the Heresy.",
        image:
          "https://m.media-amazon.com/images/I/91kxmt7iNlL._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "white scars", "primarchs"],
        link: "https://www.amazon.com/Scars-Horus-Heresy-Chris-Wraight/dp/1849706069",
        rating: null,
        quotes: "",
        summary: "",
      },

      // {
      //   title: "Wolf King",
      //   author: "",
      //   pages: 0,
      //   desc: "",
      //   image: "",
      //   isFinished: false,
      //   isReading: false,
      //   tags: ["siege of terra", "horus heresy", "astartes"],
      //   link: "",
      //   rating: null,
      //   quotes: "",
      //   summary: "",
      // },
      {
        title: "Vengeful Spirit",
        author: "Graham McNeill",
        pages: 560,
        desc: "Horus, the fallen Warmaster, leads a massive assault on the world of Molech. His goal: to gain the power of the gods and seal his fate as the master of Chaos. This novel explores Horus’s growing ambition and the dark forces that shape his rise to ultimate power, as the galaxy continues to burn.",
        image:
          "https://m.media-amazon.com/images/I/81ltRDwJm-L._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "warmaster", "primarchs"],
        link: "https://www.amazon.com/Vengeful-Spirit-Horus-Heresy/dp/1849706069",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "The Damnation of Pythos",
        author: "David Annandale",
        pages: 416,
        desc: "In the aftermath of the Dropsite Massacre, the shattered remnants of three Legions—the Iron Hands, Raven Guard, and Salamanders—flee to the distant jungle world of Pythos. But they are not alone. The horrors lurking in the darkness of this cursed world are worse than they could ever imagine. As they fight for survival, the embittered survivors of Isstvan V must face their worst nightmare. Pythos will test their faith, strength, and will to endure, but for some, it will also mean damnation.",
        image:
          "https://m.media-amazon.com/images/I/91q68nqhe1L._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: [
          "siege of terra",
          "horus heresy",
          "iron hands",
          "raven guard",
          "salamanders",
        ],
        link: "https://www.amazon.com/Damnation-Pythos-Horus-Heresy/dp/1849708436",
        rating: null,
        quotes: "",
        summary: "",
      },

      {
        title: "Legacies of Betrayal",
        author: "Various Authors",
        pages: 496,
        desc: "A massive anthology of stories from the Horus Heresy, Legacies of Betrayal explores the tragic fates of those caught in the conflict. Covering a range of events across the Horus Heresy timeline, this book provides fresh insights into both well-known and obscure characters, revealing the treachery and heartbreak behind the galaxy's most devastating war.",
        image:
          "https://m.media-amazon.com/images/I/71u3BS0skNL._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "anthology", "betrayal"],
        link: "https://www.amazon.com/Legacies-Betrayal-Horus-Heresy/dp/1849708576",
        rating: null,
        quotes: "",
        summary: "",
      },

      {
        title: "Deathfire",
        author: "Nick Kyme",
        pages: 464,
        desc: "In the aftermath of the Dropsite Massacre, the Salamanders, under the leadership of their Terran-born commander, forge a dangerous path back to Nocturne. Driven by their desire to honor their fallen Primarch Vulkan, they seek to recover his body and uncover the truth behind his apparent death. Along the way, they must face the horrors of the Warp and the treacherous forces of Chaos as they attempt to bring Vulkan back from the dead.",
        image:
          "https://m.media-amazon.com/images/I/81Mj0DsDXkL._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "salamanders", "primarchs"],
        link: "https://www.amazon.com/Deathfire-Horus-Heresy-Nick-Kyme/dp/1849708568",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "War Without End",
        author: "Various Authors",
        pages: 512,
        desc: "This anthology delves into some of the lesser-known stories of the Horus Heresy, exploring the unseen moments and the forgotten heroes of the galaxy-spanning conflict. From the battles fought in the shadows to the secret missions undertaken in the name of the Emperor or the Warmaster, War Without End offers a glimpse into the countless sacrifices made during the darkest times of the Imperium.",
        image:
          "https://m.media-amazon.com/images/I/81D3bmqGmDL._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "anthology", "war"],
        link: "https://www.amazon.com/War-Without-End-Horus-Heresy/dp/1849708533",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Pharos",
        author: "Guy Haley",
        pages: 464,
        desc: "As the Traitor Legions spread their malign influence across the galaxy, the Ultramarines and their allies prepare to make their final stand at the realm of Ultramar. But hope lies in a mysterious device on the far-flung world of Sotha—the Pharos. This ancient beacon, potentially more powerful than the Astronomican itself, could be the key to turning the tide in the war. But as the Ultramarines fight to defend it, darker forces seek to harness its power for their own ends.",
        image:
          "https://m.media-amazon.com/images/I/81rL9gGZhgL._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "ultramarines", "pharos"],
        link: "https://www.amazon.com/Pharos-Horus-Heresy-Guy-Haley/dp/1784961358",
        rating: null,
        quotes: "",
        summary: "",
      },
      // {
      //   title: "The Seventh Serpent",
      //   author: "",
      //   pages: 0,
      //   desc: "",
      //   image: "",
      //   isFinished: false,
      //   isReading: false,
      //   tags: ["siege of terra", "horus heresy", "astartes"],
      //   link: "",
      //   rating: null,
      //   quotes: "",
      //   summary: "",
      // },
      // {
      {
        title: "Eye of Terra",
        author: "Various Authors",
        pages: 432,
        desc: "An anthology that delves into the heart of the war for the Imperium. Eye of Terra explores pivotal moments in the Horus Heresy from the perspectives of key characters. From the scheming Warmaster Horus to the tortured loyalists, these stories provide new insights into the events that will shape the galaxy forever.",
        image:
          "https://m.media-amazon.com/images/I/81NCF4Osy9L._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "anthology"],
        link: "https://www.amazon.com/Eye-Terra-Horus-Heresy/dp/178496280X",
        rating: null,
        quotes: "",
        summary: "",
      },
      // {
      //   title: "The Path of Heaven",
      //   author: "",
      //   pages: 0,
      //   desc: "",
      //   image: "",
      //   isFinished: false,
      //   isReading: false,
      //   tags: ["siege of terra", "horus heresy", "astartes"],
      //   link: "",
      //   rating: null,
      //   quotes: "",
      //   summary: "",
      // },
      // {
      {
        title: "The Silent War",
        author: "Various Authors",
        pages: 400,
        desc: "The Silent War tells the stories of the shadow wars fought during the Horus Heresy. From assassins stalking their prey to covert missions on distant worlds, this anthology showcases the secret battles waged away from the front lines. Featuring tales of the Alpha Legion, the Officio Assassinorum, and more, this collection reveals the deadly intrigue that helped shape the course of the Heresy.",
        image:
          "https://m.media-amazon.com/images/I/71ZkrJfExoL._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: [
          "siege of terra",
          "horus heresy",
          "assassins",
          "alpha legion",
          "anthology",
        ],
        link: "https://www.amazon.com/Silent-War-Horus-Heresy/dp/1784964500",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Angels of Caliban",
        author: "Gav Thorpe",
        pages: 480,
        desc: "The Dark Angels, led by their enigmatic Primarch Lion El'Jonson, fight to restore order to the Imperium during the chaos of the Horus Heresy. But even as they battle the forces of the Warmaster, the Lion's Legion is torn apart by internal strife. Loyalties are tested, and a dark secret threatens to unravel the Dark Angels from within, as the fate of Caliban and the Imperium itself hangs in the balance.",
        image:
          "https://m.media-amazon.com/images/I/71wr2e8EvLL._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "dark angels", "primarchs"],
        link: "https://www.amazon.com/Angels-Caliban-Horus-Heresy/dp/1784963903",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Praetorian of Dorn",
        author: "John French",
        pages: 464,
        desc: "Rogal Dorn, Primarch of the Imperial Fists, is charged with defending Terra itself against the impending invasion of Horus's forces. As the traitor legions close in on the Throneworld, the Alpha Legion launches a cunning assault. This novel follows Dorn as he faces the ultimate test of his leadership and honor, while Alpharius and his Legion weave a deadly web of deceit that could spell doom for the Imperium.",
        image:
          "https://m.media-amazon.com/images/I/71pPh0XXAOL._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: [
          "siege of terra",
          "horus heresy",
          "imperial fists",
          "alpha legion",
        ],
        link: "https://www.amazon.com/Praetorian-Dorn-Horus-Heresy/dp/1784965132",
        rating: null,
        quotes: "",
        summary: "",
      },
      // {
      //   title: "Corax",
      //   author: "",
      //   pages: 0,
      //   desc: "",
      //   image: "",
      //   isFinished: false,
      //   isReading: false,
      //   tags: ["siege of terra", "horus heresy", "astartes"],
      //   link: "",
      //   rating: null,
      //   quotes: "",
      //   summary: "",
      // },
      // {
      //   title: "The Master of Mankind",
      //   author: "",
      //   pages: 0,
      //   desc: "",
      //   image: "",
      //   isFinished: false,
      //   isReading: false,
      //   tags: ["siege of terra", "horus heresy", "astartes"],
      //   link: "",
      //   rating: null,
      //   quotes: "",
      //   summary: "",
      // },
      // {
      //   title: "Garro: Weapon of Fate",
      //   author: "",
      //   pages: 0,
      //   desc: "",
      //   image: "",
      //   isFinished: false,
      //   isReading: false,
      //   tags: ["siege of terra", "horus heresy", "astartes"],
      //   link: "",
      //   rating: null,
      //   quotes: "",
      //   summary: "",
      // },
      // {

      {
        title: "The Crimson King",
        author: "Graham McNeill",
        pages: 560,
        desc: "Broken by the betrayal of his closest brother and the losses his Legion has suffered, Magnus the Red retreats to his homeworld of Prospero. But even there, the shattered remains of the Thousand Sons find no peace. The Crimson King must now reckon with the full consequences of his decisions and face his ultimate fate as the galaxy descends further into chaos.",
        image:
          "https://m.media-amazon.com/images/I/71u0tftBCZL._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: [
          "siege of terra",
          "horus heresy",
          "thousand sons",
          "magnus the red",
        ],
        link: "https://www.amazon.com/Crimson-King-Horus-Heresy/dp/1784967119",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Ruinstorm",
        author: "David Annandale",
        pages: 352,
        desc: "Imperium Secundus stands on the brink of disaster as the Ruinstorm tears apart the galaxy. Roboute Guilliman, Sanguinius, and Lion El’Jonson must make their perilous journey through this maelstrom of warp-spawned nightmares to reach Terra before it’s too late. But can they navigate the darkest horrors of the Ruinstorm and find a way to unite the shattered Imperium?",
        image:
          "https://m.media-amazon.com/images/I/91L7CB-JRbL._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "ruinstorm", "primarchs"],
        link: "https://www.amazon.com/Ruinstorm-Horus-Heresy-David-Annandale/dp/1784966716",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Old Earth",
        author: "Nick Kyme",
        pages: 528,
        desc: "The Salamanders set off on a quest to return Vulkan to Terra and restore their Primarch. But this journey is not without peril. Old enemies resurface, and old loyalties are tested as the Salamanders fight to overcome the dark forces that threaten their mission. Vulkan's fate, and that of the entire Imperium, hangs in the balance.",
        image:
          "https://m.media-amazon.com/images/I/71WEIbLhCnL._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "salamanders"],
        link: "https://www.amazon.com/Old-Earth-Horus-Heresy/dp/1784964594",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Wolfsbane",
        author: "Guy Haley",
        pages: 432,
        desc: "The time has come for Leman Russ, Primarch of the Space Wolves, to enact his ultimate plan—to take the fight to Horus and confront the Warmaster himself. But as Russ gathers his forces and embarks on a fateful mission, he must also contend with the curse that haunts his Legion and threatens to tear them apart from within.",
        image:
          "https://m.media-amazon.com/images/I/81dhpyKNNgL._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "space wolves"],
        link: "https://www.amazon.com/Wolfsbane-Horus-Heresy-Guy-Haley/dp/1784967321",
        rating: null,
        quotes: "",
        summary: "",
      },

      {
        title: "Slaves to Darkness",
        author: "John French",
        pages: 480,
        desc: "Horus Lupercal has unleashed his forces to begin the final assault on Terra. But before the Siege of Terra can begin, he must gather his fractured armies. This novel chronicles Horus's efforts to bind his forces together, while also exploring the tragic fates of the traitor legions as they descend further into madness and damnation.",
        image:
          "https://m.media-amazon.com/images/I/81RTzHUvoFL._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "traitor legions", "chaos"],
        link: "https://www.amazon.com/Slaves-Darkness-Horus-Heresy/dp/1784968573",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Titandeath",
        author: "Guy Haley",
        pages: 432,
        desc: "The galaxy is aflame as the Loyalist and Traitor forces clash in titanic battles across the stars. This novel focuses on the apocalyptic war between the massive god-machines of the Adeptus Titanicus. As the forces of Horus and the Emperor battle for supremacy, the Titans march to war in the largest engagements the galaxy has ever seen.",
        image:
          "https://m.media-amazon.com/images/I/91HgnmFQO9L._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "titans"],
        link: "https://www.amazon.com/Titandeath-Horus-Heresy-Guy-Haley/dp/1784968190",
        rating: null,
        quotes: "",
        summary: "",
      },

      {
        title: "The Buried Dagger",
        author: "James Swallow",
        pages: 400,
        desc: "As the galaxy burns in the fires of treachery, the Death Guard faces its darkest hour. Mortarion, their Primarch, and his sons must confront the horrors that await them in the Warp. This novel charts the Death Guard’s descent into madness and decay, revealing the roots of their damnation and their ultimate transformation into the Plague Marines of Nurgle.",
        image:
          "https://m.media-amazon.com/images/I/81W73F3TGOL._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "death guard", "mortarion"],
        link: "https://www.amazon.com/Buried-Dagger-Horus-Heresy/dp/1784969367",
        rating: null,
        quotes: "",
        summary: "",
      },

      {
        title: "The Solar War",
        author: "John French",
        pages: 432,
        desc: "The Imperium faces its greatest threat as the forces of Chaos invade Terra. This novel chronicles the Solar War, showcasing the desperate battle for the soul of humanity. Heroes will rise and fall as the last stand against the forces of Chaos unfolds, leading to devastating consequences for all involved.",
        image:
          "https://m.media-amazon.com/images/I/91v9OXKkEtL._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "chaos", "astartes"],
        link: "https://www.amazon.com/Solar-War-Horus-Heresy/dp/1784968847",
        rating: null,
        quotes: "",
        summary: "",
      },

      {
        title: "The Lost and the Damned",
        author: "Guy Haley",
        pages: 416,
        desc: "The final push of Horus’s forces has begun. As the traitors descend upon Terra, the Loyalists must rally to defend humanity’s last bastion. This novel tells the story of the climactic battles of the Siege of Terra, exploring the horrors of war and the depths of betrayal as the fate of the Imperium hangs in the balance.",
        image:
          "https://m.media-amazon.com/images/I/81GnvS9hj8L._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "https://www.amazon.com/Lost-Damned-Horus-Heresy/dp/1784968860",
        rating: null,
        quotes: "",
        summary: "",
      },

      {
        title: "The First Wall",
        author: "Ian St. Martin",
        pages: 416,
        desc: "The Siege of Terra continues, with the Imperial forces under attack. The story follows the battles and the defenders of the Imperial Palace as they fight to withstand the traitors' onslaught. With sacrifices made on all sides, the struggle for survival becomes increasingly desperate.",
        image:
          "https://m.media-amazon.com/images/I/81toZfV2LpL._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "astartes"],
        link: "https://www.amazon.com/First-Wall-Horus-Heresy/dp/1784968847",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Sons of the Selenar",
        author: "Graham McNeill",
        pages: 128,
        desc: "Set during the Siege of Terra, this novella follows Captain Tyro and his team as they try to prevent the Sons of Horus from uncovering a powerful secret held by the gene-cultists known as the Selenar. This mission could change the fate of the galaxy itself.",
        image:
          "https://m.media-amazon.com/images/I/91HgnmFQO9L._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["horus heresy", "siege of terra", "gene-cultists"],
        link: "https://www.amazon.com/Sons-Selenar-Horus-Heresy-Novella/dp/178999190X",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Saturnine",
        author: "Dan Abnett",
        pages: 448,
        desc: "The battle for Terra continues as Rogal Dorn's defenses falter, and the Traitors make their most devastating assault yet. Heroes and villains alike make their stand in this turning point of the Siege.",
        image:
          "https://m.media-amazon.com/images/I/81EVhC1y4zL._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "warhammer 40k"],
        link: "https://www.amazon.com/Saturnine-Horus-Heresy-Siege-Terra/dp/178999308X",
        rating: null,
        quotes: "",
        summary: "",
      },

      // {
      //   title: "The Fury of Magnus",
      //   author: "Graham McNeill",
      //   pages: 0,
      //   desc: "",
      //   image: "",
      //   isFinished: false,
      //   isReading: false,
      //   tags: ["siege of terra", "astartes"],
      //   link: "",
      //   rating: null,
      //   quotes: "",
      //   summary: "",
      // },
      // {
      {
        title: "Mortis",
        author: "John French",
        pages: 400,
        desc: "As the traitor forces, led by the Legio Mortis Titans, break through to the inner sanctums of Terra, the fate of the Imperium hangs in the balance.",
        image:
          "https://m.media-amazon.com/images/I/81NyAzVDJwL._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "titans"],
        link: "https://www.amazon.com/Mortis-Siege-Terra-Horus-Heresy/dp/1789991958",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Warhawk",
        author: "Chris Wraight",
        pages: 400,
        desc: "Jaghatai Khan leads the White Scars in a daring charge to retake the Lion’s Gate Spaceport in a critical battle for control of Terra's surface.",
        image:
          "https://m.media-amazon.com/images/I/81cuoMSiAbL._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "white scars"],
        link: "https://www.amazon.com/Warhawk-Horus-Heresy-Siege-Terra/dp/178999308X",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Echoes of Eternity",
        author: "Aaron Dembski-Bowden",
        pages: 400,
        desc: "The Emperor’s Palace is besieged, and Sanguinius fights to defend it against the endless tide of the Traitors while confronting his own grim destiny.",
        image:
          "https://m.media-amazon.com/images/I/81nhKgMk+4L._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy", "sanguinius"],
        link: "https://www.amazon.com/Echoes-Eternity-Horus-Heresy/dp/1800260347",
        rating: null,
        quotes: "",
        summary: "",
      },
      // {
      //   title: "Garro: Knight of Grey",
      //   author: "James Swallow",
      //   pages: 0,
      //   desc: "",
      //   image: "",
      //   isFinished: false,
      //   isReading: false,
      //   tags: ["siege of terra", "astartes"],
      //   link: "",
      //   rating: null,
      //   quotes: "",
      //   summary: "",
      // },
      {
        title: "The End and the Death - Volume I",
        author: "Dan Abnett",
        pages: 672,
        desc: "There is no way out. The walls have fallen, the gates are breached, and the defenders are slain. It is the end and the death. After seven brutal years of civil war, the Warmaster stands on the verge of victory. Horus Lupercal, once beloved son, has come to murder his father. The Emperor, a shining beacon of hope to many, an unscrupulous tyrant to others, must die. The lives of uncountable numbers have been extinguished and even primarchs, once thought immortal, have been laid low. The Emperor’s dream lies in tatters, but there remains a sliver of hope. Now, at the final hour of the final day, the Emperor rises. With him come his Angel, his Praetorian, and his Captain, all determined to enact terrible vengeance. Yet the hope is slim, for the Warmaster sees all and knows all, and the ultimate victory of Chaos is at hand. There is no way out.",
        image:
          "https://m.media-amazon.com/images/I/81-Pu-0-MqL._AC_UY327_FMwebp_QL65_.jpg",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "horus heresy"],
        link: "https://www.amazon.com/End-Death-I-Dan-Abnett/dp/1804076414",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "The End and the Death: Volume II",
        author: "Dan Abnett",
        pages: 672,
        desc: "Terra is besieged. Humanity’s salvation lies on a knife edge. The Warmaster Horus’ bloody seven-year crusade has led to this: the cradle of mankind, where he is to kill his father, the Emperor.   With the war at this critical juncture, Sanguinius, primarch of the loyalist Blood Angels, braves the horrors of the Warmaster’s flagship, The Vengeful Spirit, with a single purpose in mind: to slay his brother Horus, decapitate the Heresy once and for all, and stop the forces of Chaos from taking Holy Terra. But at the whim of a Warmaster fallen so far from grace, the Dark Gods will not make Sanguinius’ task an easy one, and as the war edges towards its explosive, bloody conclusion, events are about to unfold that could either save humanity, or plunge it headlong into an eternity of darkness.",
        image: "",
        isFinished: false,
        isReading: false,
        tags: ["siege of terra", "astartes"],
        link: "https://www.amazon.com/End-Death-II-Dan-Abnett/dp/1804073547",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Roboute Guilliman: Lord of Ultramar",
        author: "David Annandale",
        pages: 224,
        desc: "This book explores Roboute Guilliman's leadership and his role in the Great Crusade, focusing on his legion and strategy.",
        image:
          "https://m.media-amazon.com/images/I/81XWJ1guHnL._AC_UY327_FMwebp_QL65_.jpg",
        tags: ["horus heresy", "primarch", "Ultramarines"],
        link: "https://www.amazon.com/dp/B01MU3D99G",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Leman Russ: The Great Wolf",
        author: "Chris Wraight",
        pages: 208,
        desc: "A tale of Leman Russ and his Space Wolves, highlighting his ferocity and honor during the Crusade.",
        image:
          "https://m.media-amazon.com/images/I/91Y92AZlJ7L._AC_UY327_FMwebp_QL65_.jpg",
        tags: ["horus heresy", "primarch", "Space Wolves"],
        link: "https://www.amazon.com/dp/B073SRQ21D",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Magnus the Red: Master of Prospero",
        author: "Graham McNeill",
        pages: 192,
        desc: "Magnus the Red's powerful psychic abilities come into focus as he leads his legion through the Great Crusade.",
        image:
          "https://m.media-amazon.com/images/I/81Tnmc5gT7L._AC_UY327_FMwebp_QL65_.jpg",
        tags: ["horus heresy", "primarch", "Thousand Sons"],
        link: "https://www.amazon.com/dp/B0762RS6MK",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Perturabo: Hammer of Olympia",
        author: "Guy Haley",
        pages: 192,
        desc: "The tale of Perturabo, the master of siege warfare, and his role in shaping the future of the Iron Warriors.",
        image:
          "https://m.media-amazon.com/images/I/81O3aTfpSmL._AC_UY327_FMwebp_QL65_.jpg",
        tags: ["horus heresy", "primarch", "Iron Warriors"],
        link: "https://www.amazon.com/dp/B06XSTMPXC",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Lorgar: Bearer of the Word",
        author: "Gav Thorpe",
        pages: 192,
        desc: "Lorgar, the primarch of the Word Bearers, and his journey into fanaticism and faith, leading to the Horus Heresy.",
        image:
          "https://m.media-amazon.com/images/I/71hnMJnCpWL._AC_UY327_FMwebp_QL65_.jpg",
        tags: ["horus heresy", "primarch", "Word Bearers"],
        link: "https://www.amazon.com/dp/B075MY15HV",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Fulgrim: The Palatine Phoenix",
        author: "Josh Reynolds",
        pages: 192,
        desc: "Fulgrim's obsession with perfection leads him to his eventual fall, making him a key figure in the Horus Heresy.",
        image:
          "https://m.media-amazon.com/images/I/81i6PiY98kL._AC_UY327_FMwebp_QL65_.jpg",
        tags: ["horus heresy", "primarch", "Emperor's Children"],
        link: "https://www.amazon.com/dp/B07BBQVZWV",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Ferrus Manus: The Gorgon of Medusa",
        author: "David Guymer",
        pages: 192,
        desc: "The story of Ferrus Manus, the Primarch of the Iron Hands, focusing on his role as a relentless warrior and craftsman.",
        image:
          "https://m.media-amazon.com/images/I/81W9wZSkRzL._AC_UY327_FMwebp_QL65_.jpg",
        tags: ["horus heresy", "primarch", "Iron Hands"],
        link: "https://www.amazon.com/dp/B07D8JQ52P",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Jaghatai Khan: Warhawk of Chogoris",
        author: "Chris Wraight",
        pages: 192,
        desc: "A tale of Jaghatai Khan, the Primarch of the White Scars, and his daring tactics during the Great Crusade.",
        image:
          "https://m.media-amazon.com/images/I/81c1np04m5L._AC_UY327_FMwebp_QL65_.jpg",
        tags: ["horus heresy", "primarch", "White Scars"],
        link: "https://www.amazon.com/dp/B07GT9V3MR",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Vulkan: Lord of Drakes",
        author: "David Annandale",
        pages: 192,
        desc: "Vulkan’s character is shaped by his bond with his sons, the Salamanders, as he defends humanity and its future.",
        image:
          "https://m.media-amazon.com/images/I/81m2TLqi3kL._AC_UY327_FMwebp_QL65_.jpg",
        tags: ["horus heresy", "primarch", "Salamanders"],
        link: "https://www.amazon.com/dp/B07N7K1JMK",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Corax: Lord of Shadows",
        author: "Guy Haley",
        pages: 192,
        desc: "Corax, the Primarch of the Raven Guard, leads his legion through covert operations and guerrilla warfare in the Great Crusade.",
        image:
          "https://m.media-amazon.com/images/I/81kWSXIRCyL._AC_UY327_FMwebp_QL65_.jpg",
        tags: ["horus heresy", "primarch", "Raven Guard"],
        link: "https://www.amazon.com/dp/B07ZKNB8TR",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Angron: Slave of Nuceria",
        author: "Ian St. Martin",
        pages: 192,
        desc: "Angron's tragic past as a gladiator on Nuceria and his brutal rise as the Primarch of the World Eaters are revealed.",
        image:
          "https://m.media-amazon.com/images/I/81cEYwXedbL._AC_UY327_FMwebp_QL65_.jpg",
        tags: ["horus heresy", "primarch", "World Eaters"],
        link: "https://www.amazon.com/dp/B07Z7K9YV7",
        rating: null,
        quotes: "",
        summary: "",
      },
      {
        title: "Konrad Curze: The Night Haunter",
        author: "Guy Haley",
        pages: 192,
        desc: "Konrad Curze, the Night Haunter, is a chilling figure who uses terror as a weapon, leading his Night Lords into darkness.",
        image:
          "https://m.media-amazon.com/images/I/91eKTl2K7BL._AC_UY327_FMwebp_QL65_.jpg",
        tags: ["horus heresy", "primarch", "night lords"],
        link: "https://www.amazon.com/dp/B083C6TQ7T",
        rating: null,
        quotes: "",
        summary: "",
      },
      // {
      //   title: "Lion El'Jonson: Lord of the First",
      //   author: "David Guymer",
      //   pages: 0,
      //   desc: "",
      //   image: "",
      //   isFinished: false,
      //   isReading: false,
      //   tags: ["siege of terra", "primarch", "astartes", "dark angels"],
      //   link: "",
      //   rating: null,
      //   quotes: "",
      //   summary: "",
      // },
      // {
      //   title: "Alpharius: Head of the Hydra",
      //   author: "Mike Brooks",
      //   pages: 0,
      //   desc: "",
      //   image: "",
      //   isFinished: false,
      //   isReading: false,
      //   tags: ["siege of terra", "primarch", "astartes", "alpha legion"],
      //   link: "",
      //   rating: null,
      //   quotes: "",
      //   summary: "",
      // },
      // {
      //   title: "Mortarion: The Pale King",
      //   author: "David Annandale",
      //   pages: 0,
      //   desc: "",
      //   image: "",
      //   isFinished: false,
      //   isReading: false,
      //   tags: ["siege of terra", "primarch", "astartes", "death guard"],
      //   link: "",
      //   rating: null,
      //   quotes: "",
      //   summary: "",
      // },
      // {
      //   title: "Rogal Dorn: The Emperor's Crusader",
      //   author: "Gav Thorpe",
      //   pages: 0,
      //   desc: "",
      //   image: "",
      //   isFinished: false,
      //   isReading: false,
      //   tags: ["siege of terra", "primarch", "astartes", "imperial fists"],
      //   link: "",
      //   rating: null,
      //   quotes: "",
      //   summary: "",
      // },
      // {
      //   title: "Sanguinius: The Great Angel",
      //   author: "Chris Wraight",
      //   pages: 0,
      //   desc: "",
      //   image: "",
      //   isFinished: false,
      //   isReading: false,
      //   tags: ["siege of terra", "primarch", "astartes", "blood angels"],
      //   link: "",
      //   rating: null,
      //   quotes: "",
      //   summary: "",
      // },
      //  { title: "The Infinite and The Divine",
      //   author: "Robert Rath",
      //   pages: 368,
      //   desc: "Before the being called the Emperor revealed Himself, before the rise of the aeldari, before the necrontyr traded their flesh for immortal metal, the world was born in violence.Even when they inhabited bodies of flesh, Trazyn the Infinite and Orikan the Diviner were polar opposites. Trazyn, a collector of historical oddities, presides over a gallery full of the most dangerous artefacts – and people – of the galactic past. Orikan, a chronomancer without peer, draws zodiacs that predict and manipulate the future. But when an artefact emerges that may hold the key to the necrons’ next evolution, these two obsessives enter a multi-millennia game of cat and mouse that ends civilisations, reshapes timelines, and changes both forever. As riddles unwind and ancient secrets are revealed, the question remains: will their feud save the necron race or destroy it?",
      //   image: "",
      //   isFinished: false,
      //   isReading: false,
      //   tags: ["trazyn the infinite", "necrons"],
      //   link: "https://www.amazon.com/Infinite-Divine-Warhammer-40-000/dp/1789998328",
      //   rating: null,
      //   quotes: "",
      //   summary: "",
      // },
      // {
      //   title: "The Twice Dead King: Ruin",
      //   author: "Nate Crowley",
      //   pages: 370,
      //         desc: "Exiled to the miserable world of Sedh, the disgraced Necron Lord Oltyx is consumed with bitterness. Once heir to the throne of a dynasty, he now commands nothing but a dwindling garrison of warriors, in a never-ending struggle against Ork invaders. Oltyx can think of nothing but the prospect of vengeance against his betrayers, and the reclamation of his birthright. But the Orks are merely the harbingers of a truly unstoppable force. Unless Oltyx acts to save his dynasty, revenge will win him only ashes. And so he must return to the crownworld, and to the heart of the very court which cast him out. But what awaits there is a horror more profound than any invader, whose roots are tangled with the dark origins of the Necrons themselves."
      //     image: "",
      //   isFinished: false,
      //   isReading: false,
      //   tags: [ "necrons"],
      //   link: "https://www.amazon.com/Twice-Dead-King-Ruin-Warhammer-ebook/dp/B09GFM6M11",
      //   rating: null,
      //   quotes: "",
      //   summary: "",
      // },

      // {
      //   title: "Eisenhorn: The Omnibus",
      //   author: "Dan Abnett",
      //   pages:944 ,
      //   desc:"In the grim far future, the Inquisition moves amongst mankind like an avenging shadow, striking down daemons, aliens and heretics with uncompromising ruthlessness. Written by Gaunt’s Ghosts creator, Dan Abnett, this volume charts the career of Inquisitor Gregor Eisenhorn as he changes from being a zealous upholder of the truth to collaborating with the very powers he once swore to destroy. Part detective story, part interplanetary Epic, this omnibus brings together the novels Xenos, Malleus, Hereticus and The Magos, as well as four short stories."
      //   image: "",
      //   isFinished: false,
      //   isReading: false,
      //   tags: [ "eisenhorn", "inquisitors", "omnibus"],
      //   link: "https://www.amazon.com/Eisenhorn-Omnibus-Warhammer-40-000/dp/1789990548",
      //   rating: null,
      //   quotes: "",
      //   summary: "",
      // },
      // {
      //   title: "Lords of Nocturne: A Salamanders Omnibus",
      //   author: "Nick Kyme",
      //   pages: 800 ,
      //   desc:"After the death of their captain at the hands of a traitorous brother, Da’kir and Tsu’gan, battle-brothers and rivals, face enemies from within and without. As their paths diverge and they face trials that will test them to their very limits, their destinies draw them back together for one final confrontation that will decide the fate of the Salamanders Chapter. The Salamanders, fire-born sons of Vulkan, unite to face a threat to their very existence in this omnibus edition of tales from Nick Kyme."
      //   image: "",
      //   isFinished: false,
      //   isReading: false,
      //   tags: [ "astartes", "salamanders", "omnibus""],
      //   link: "https://www.amazon.com/Lords-Nocturne-Salamanders-Omnibus-Warhammer/dp/1804075566",
      //   rating: null,
      //   quotes: "",
      //   summary: "",
      // },
      // {
      //   title: "Deathwatch: The Omnibus",
      //   author: "David Annandale and more",
      //   pages:  1239,
      //   desc:"The Deathwatch are the elite. Recruited from numerous Space Marine Chapters, their mission is simple: exterminate any xenos threat to the Imperium. Assembled into kill-teams, the Deathwatch are expert alien hunters, equipped to undertake any mission in any environment. None are as dedicated or as skilled in the brutal art of alien annihilation. This action-packed omnibus contains three full novels written by Steve Parker, Ian St Martin and Justin D Hill, along with a dozen of the best short stories ever written about the Imperium’s premier xenos hunters.

      //   image: "",
      //   isFinished: false,
      //   isReading: false,
      //   tags: [ "deathwatch", "omnibus"],
      //   link: "https://www.amazon.com/Deathwatch-Omnibus-Warhammer-40-000-ebook/dp/B076JGFJBT",
      //   rating: null,
      //   quotes: "",
      //   summary: "",
      // },
      // {
      //   title: "Salamanders: The Omnibus",
      //   author: "Nick Kyme",
      //   pages: 1560 ,
      //   desc:"The Salamanders have a long and noble history, standing proud among the First Founding Space Marine Chapters. Though their appearance can be terrifying, they are deeply honourable, and will go to any lengths to safeguard the Imperium and its billions of teeming citizens. After the death of their captain, Da’kir and Tsu’gan, battlebrothers and rivals, face enemies from within and without. As their paths diverge and they face trials that will test them to their very limits, their destinies draw them back together for one final confrontation... New edition of a greatvalue omnibus that contains all three novels in the Tome of Fire trilogy Salamander, Firedrake and Nocturne plus a host of additional short stories."
      //   image: "",
      //   isFinished: false,
      //   isReading: false,
      //   tags: [ "astartes" "salamanders" , "omnibus"],
      //   link: "https://www.amazon.com/Salamanders-Omnibus-Warhammer-40-000-ebook/dp/B07CP68ZM9",
      //   rating: null,
      //   quotes: "",
      //   summary: "",
      // },
      // {
      //   title: "The Grey Knights Omnibus",
      //   author: "Ben Counter",
      //   pages: 739 ,
      //   desc:"The Grey Knights are servants of the Ordo Malleus, imperious, incorruptible warriors, whose very purpose is to seek out and destroy the most dangerous foes that humanity will ever face; daemons. Armed and armoured with the trappings of a daemonhunter, these stalwart Adeptus Astartes bring death and destruction to the immortal denizens of the warp. Girded by faith, wielders of the nemesis force halberd, the Grey Knights step where others will not tread. Theirs is the hardest task, risking their immortal souls in pursuit of the hungry entities of Chaos, the Imperium's arch foes. Without the Grey Knights, humanity would be but a feast on the sacrificial altar of darkness..."
      //   image: "",
      //   isFinished: false,
      //   isReading: false,
      //   tags: [ "grey knights", omnibus],
      //   link: " https://www.amazon.com/Grey-Knights-Omnibus-Warhammer-000-ebook/dp/B01N1FRMZ4",
      //   rating: null,
      //   quotes: "",
      //   summary: "",
      // },
      // {
      //   title: "",
      //   author: "",
      //   pages: ,
      //   desc:""
      //   image: "",
      //   isFinished: false,
      //   isReading: false,
      //   tags: [ ""],
      //   link: "",
      //   rating: null,
      //   quotes: "",
      //   summary: "",
      // },
      // {
      //   title: "",
      //   author: "",
      //   pages: ,
      //   desc:""
      //   image: "",
      //   isFinished: false,
      //   isReading: false,
      //   tags: [ ""],
      //   link: "",
      //   rating: null,
      //   quotes: "",
      //   summary: "",
      // },
      // {
      //   title: "",
      //   author: "",
      //   pages: ,
      //   desc:""
      //   image: "",
      //   isFinished: false,
      //   isReading: false,
      //   tags: [ ""],
      //   link: "",
      //   rating: null,
      //   quotes: "",
      //   summary: "",
      // },
      // {
      //   title: "",
      //   author: "",
      //   pages: ,
      //   desc:""
      //   image: "",
      //   isFinished: false,
      //   isReading: false,
      //   tags: [ ""],
      //   link: "",
      //   rating: null,
      //   quotes: "",
      //   summary: "",
      // },
    ],
  });
}

main()
